### ISSUE TITLE
s/master/main/ ?

### ISSUE THREAD

**Issue by RichiH** [denog/chatterliste#101]
As far as I could see, we can simply switch the main branch to, well, main, as we're using GitHub pages, that is set to build for all branches, and as https://www.denog.de/de/chatterliste_iframe.html uses an iframe to point to the GitHub page.

Can we just follow https://github.com/github/renaming and done? Or is this more involved?

**Comment by apparentorder** [comment]
That's some loud silence here.

I don't think this is for me to comment on, but since nobody else is jumping in ... FWIW, I'm not aware of anything we'd have to consider besides GH Pages, which should be fine, as you said. The GH Action (validation) looks like it should be fine too.

So if this matters to you and nobody else chimes in, I'd say go for it.

**Comment by awlx** [comment]
I did the necessary changes and consider this done. :) @RichiH 

<img width="872" alt="Screenshot 2021-05-04 at 16 25 25" src="https://user-images.githubusercontent.com/6527744/117019046-594b3c80-acf5-11eb-808d-b05bbeb4729e.png">

**Comment by RichiH** [comment]
@apparentorder sorry, I missed the mail with your comment :(

@awlx Noice. Thanks!
